stages:
  - name: check configuration
    if: branch = travis
  - name: deploy
    if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  include:
    - stage: check configuration
      before_script: source ./packaging/prepare.sh
      script: ./packaging/test.sh
    - stage: deploy
      before_script: source ./packaging/prepare.sh
      script: ./packaging/deploy.sh
